openspending/forum/forum/forms.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.forms
    ~~~~~~~~~~~~~~~~~~~~

    It provides the forms that are needed for the forum views.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask_wtf import Form
from wtforms import (TextAreaField, StringField, SelectMultipleField,
                     BooleanField, SubmitField)
from wtforms.validators import DataRequired, Optional, Length
from flask_babelex import lazy_gettext as _

from openspending.forum.forum.models import Topic, Post, Report, Forum
from openspending.model.account import Account as User


class QuickreplyForm(Form):
    content = TextAreaField(_("Quick Reply"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    submit = SubmitField(_("Reply"))

    def save(self, user, topic):
        post = Post(content=self.content.data)
        return post.save(user=user, topic=topic)


class ReplyForm(Form):
    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this Topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Reply"))
    preview = SubmitField(_("Preview"))

    def save(self, user, topic):
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return post.save(user=user, topic=topic)


class NewTopicForm(ReplyForm):
    title = StringField(_("Topic Title"), validators=[
        DataRequired(message=_("Please choose a Topic Title."))])

    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this Topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Post Topic"))
    preview = SubmitField(_("Preview"))

    def save(self, user, forum):
        topic = Topic(title=self.title.data)
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return topic.save(user=user, forum=forum, post=post)


class ReportForm(Form):
    reason = TextAreaField(_("Reason"), validators=[
        DataRequired(message=_("What's the reason for reporting this post?"))
    ])

    submit = SubmitField(_("Report Post"))

    def save(self, user, post):
        report = Report(reason=self.reason.data)
        return report.save(post=post, user=user)


# class UserSearchForm(Form):
#     search_query = StringField(_("Search"), validators=[
#         Optional(), Length(min=3, max=50)
#     ])

#     submit = SubmitField(_("Search"))

#     def get_results(self):
#         query = self.search_query.data
#         return User.query.whoosh_search(query)


class SearchPageForm(Form):
    search_query = StringField(_("Searh Terms"), validators=[
        DataRequired(), Length(min=3, max=50)])

    search_types = SelectMultipleField(_("Content"), validators=[
        DataRequired()], choices=[('post', _('Post')), ('topic', _('Topic')),
                                  ('forum', _('Forum'))])

    submit = SubmitField(_("Search"))

    def get_results(self):
        # Because the DB is not yet initialized when this form is loaded,
        # the query objects cannot be instantiated in the class itself
        search_actions = {
            'post': Post.query.whoosh_search,
            'topic': Topic.query.whoosh_search,
            'forum': Forum.query.whoosh_search,
        }

        query = self.search_query.data
        types = self.search_types.data
        results = {}

        for search_type in search_actions.keys():
            if search_type in types:
                results[search_type] = search_actions[search_type](query)

        return results

openspending/forum/forum/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.views
    ~~~~~~~~~~~~~~~~~~~~

    This module handles the forum logic like creating and viewing
    topics and posts.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import datetime

from flask import (Blueprint, redirect, url_for, current_app,
                   request, flash, jsonify, render_template)
from flask_login import login_required, current_user
from flask_babelex import gettext as _

from openspending.core import db
from openspending.forum.utils.forum_settings import flaskbb_config
from openspending.forum.utils.helpers import (get_online_users, time_diff, format_quote,
                                   do_topic_action)
from openspending.auth.perms import (can_post_reply, can_post_topic,
                                       can_delete_topic, can_delete_post,
                                       can_edit_post, can_moderate)
from openspending.auth import authenticated_required
from openspending.forum.forum.models import (Category, Forum, Topic, Post, ForumsRead,
                                  TopicsRead)
from openspending.forum.forum.forms import (QuickreplyForm, ReplyForm, NewTopicForm,
                                 ReportForm, SearchPageForm)
from openspending.model.account import Account as User

forum = Blueprint("forum", __name__)


@forum.route("/")
@authenticated_required
def index():
    categories = Category.get_all(user=current_user)

    # Fetch a few stats about the forum
    user_count = User.query.count()
    topic_count = Topic.query.count()
    post_count = Post.query.count()
    newest_user = User.query.order_by(User.id.desc()).first()


    # online_users = len(get_online_users())
    # online_guests = len(get_online_users(guest=True))

    return render_template("forum/forum/index.html",
                           categories=categories,
                           user_count=user_count,
                           topic_count=topic_count,
                           post_count=post_count,
                           newest_user=newest_user)
                           # online_users=online_users,
                           # online_guests=online_guests)


@forum.route("/category/<int:category_id>")
@forum.route("/category/<int:category_id>-<slug>")
@authenticated_required
def view_category(category_id, slug=None):
    return redirect(url_for("forum.index"))
    # category, forums = Category.\
    #     get_forums(category_id=category_id, user=current_user)

    # return render_template("forum/forum/category.html", forums=forums,
    #                        category=category)


@forum.route("/forum/<int:forum_id>")
@forum.route("/forum/<int:forum_id>-<slug>")
def view_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id,
                                                 user=current_user)

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(
        forum_id=forum_instance.id, user=current_user, page=page,
        per_page=flaskbb_config["TOPICS_PER_PAGE"])

    return render_template(
        "forum/forum/forum.html", forum=forum_instance,
        topics=topics, forumsread=forumsread,
        flaskbb_config=flaskbb_config
    )


@forum.route("/topic/<int:topic_id>", methods=["POST", "GET"])
@forum.route("/topic/<int:topic_id>-<slug>", methods=["POST", "GET"])
def view_topic(topic_id, slug=None):
    page = request.args.get('page', 1, type=int)

    # Fetch some information about the topic
    topic = Topic.get_topic(topic_id=topic_id, user=current_user)

    # Count the topic views
    topic.views += 1
    topic.save()

    # fetch the posts in the topic
    posts = Post.query.\
        join(User, Post.user_id == User.id).\
        filter(Post.topic_id == topic.id).\
        add_entity(User).\
        order_by(Post.id.asc()).\
        paginate(page, flaskbb_config['POSTS_PER_PAGE'], False)

    # Update the topicsread status if the user hasn't read it
    forumsread = None
    if current_user.is_authenticated():
        forumsread = ForumsRead.query.\
            filter_by(user_id=current_user.id,
                      forum_id=topic.forum.id).first()

    topic.update_read(current_user, topic.forum, forumsread)

    form = None
    if can_post_reply(user=current_user, topic=topic):
        form = QuickreplyForm()
        if form.validate_on_submit():
            post = form.save(current_user, topic)
            return view_post(post.id)
    return render_template("forum/forum/topic.html", topic=topic, posts=posts,
                           last_seen=time_diff(), form=form)


@forum.route("/post/<int:post_id>")
def view_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    count = post.topic.post_count
    page = count / flaskbb_config["POSTS_PER_PAGE"]

    if count > flaskbb_config["POSTS_PER_PAGE"]:
        page += 1
    else:
        page = 1

    return redirect(post.topic.url + "?page=%d#pid%s" % (page, post.id))


@forum.route("/<int:forum_id>/topic/new", methods=["POST", "GET"])
@forum.route("/<int:forum_id>-<slug>/topic/new", methods=["POST", "GET"])
@login_required
def new_topic(forum_id, slug=None):
    forum_instance = Forum.query.filter_by(id=forum_id).first_or_404()

    if not can_post_topic(user=current_user, forum=forum_instance):
        flash(_("You do not have the permissions to create a new topic."),
              "danger")
        return redirect(forum.url)

    form = NewTopicForm()
    if request.method == "POST":
        if "preview" in request.form and form.validate():
            return render_template(
                "forum/forum/new_topic.html", forum=forum_instance,
                form=form, preview=form.content.data
            )
        if "submit" in request.form and form.validate():
            topic = form.save(current_user, forum_instance)
            # redirect to the new topic
            return redirect(url_for('forum.view_topic', topic_id=topic.id))

    return render_template(
        "forum/forum/new_topic.html", forum=forum_instance, form=form
    )


@forum.route("/topic/<int:topic_id>/delete", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/delete", methods=["POST"])
@login_required
def delete_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_delete_topic(user=current_user, topic=topic):
        flash(_("You do not have the permissions to delete this topic."),
              "danger")
        return redirect(topic.forum.url)

    involved_users = User.query.filter(Post.topic_id == topic.id,
                                       User.id == Post.user_id).all()
    topic.delete(users=involved_users)
    return redirect(url_for("forum.view_forum", forum_id=topic.forum_id))


@forum.route("/topic/<int:topic_id>/lock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/lock", methods=["POST"])
@login_required
def lock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to lock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/unlock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/unlock", methods=["POST"])
@login_required
def unlock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to unlock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = False
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/highlight", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/highlight", methods=["POST"])
@login_required
def highlight_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to highlight this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/trivialize", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/trivialize", methods=["POST"])
@login_required
def trivialize_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # Unlock is basically the same as lock
    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to trivialize this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = False
    topic.save()
    return redirect(topic.url)


@forum.route("/forum/<int:forum_id>/edit", methods=["POST", "GET"])
@forum.route("/forum/<int:forum_id>-<slug>/edit", methods=["POST", "GET"])
@login_required
def manage_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id,
                                                 user=current_user)

    # remove the current forum from the select field (move).
    available_forums = Forum.query.order_by(Forum.position).all()
    available_forums.remove(forum_instance)

    if not can_moderate(current_user, forum=forum_instance):
        flash(_("You do not have the permissions to moderate this forum."),
              "danger")
        return redirect(forum_instance.url)

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(

openspending/views/search.py
import logging

from flask import Blueprint, render_template, g, request, redirect
from werkzeug.exceptions import BadRequest

from openspending.lib.helpers import url_for, obj_or_404

from openspending.core import cache

from openspending.model import Dataset

log = logging.getLogger(__name__)
blueprint = Blueprint('search', __name__)



@blueprint.route('/search', methods=['POST'])
def search_post():
    if not g.search_form.validate_on_submit():
        return redirect(url_for('home.index'))
    return redirect(url_for('search.search_results', query=g.search_form.search.data))


@blueprint.route('/search_results/<query>')
def search_results(query):
    results = Dataset.query.whoosh_search(query).all()
    return render_template('search/search_results.jade',
                           query=query,
                           results=results)

openspending/templates/forum/forum/category.html
{% set page_title = category.title %}
{% set active_forum_nav=True %}

{% extends "forum/layout.html" %}
{% block forumcontent %}

<ol class="breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">Forum</a></li>
    <li class="active">{{ category.title }}</li>
</ol>

{% include "forum/forum/category_layout.html" %}

{% endblock %}

openspending/templates/forum/forum/category_layout.html
<table class="table table-bordered">
    <thead class="categoryhead">
        <tr>
            <td colspan="5">
                <div><strong>{{ category.title }}</strong></div>
            </td>
        </tr>
    </thead>
    <tbody class="forumbody">
        <tr class="forum_stats">
            <td colspan="2"><strong>Forum</strong></td>
            <td width="85" align="center" style="white-space: nowrap"><strong>Topics</strong></td>
            <td width="85" align="center" style="white-space: nowrap"><strong>Posts</strong></td>
            <td width="200" align="center" style="white-space: nowrap"><strong>Last Post</strong></td>
        </tr>

        {% for forum, forumsread in forums %}
        <tr>
            <td align="center" valign="center" width="4%">

            {% if forum.external %}
                <span class="fa fa-external-link" style="font-size: 2em"></span>
            </td>

            <td valign="top">
                <strong><a href="{{ forum.external }}">{{ forum.title }}</a></strong>

                <div class="forum-description">
                    {% autoescape false %}
                    {{ forum.description|markup }}
                    {% endautoescape %}
                </div>
            </td>

            <td valign="top" align="center" style="white-space: nowrap">-</td>
            <td valign="top" align="center" style="white-space: nowrap">-</td>
            <td valign="top" align="right" style="white-space: nowrap">-</td>
            <!-- End external -->
            {% else %}

            {% if forum.locked %}
                <span class="fa fa-lock" style="font-size: 2em"></span>
            {% elif forum %}
                <span class="fa fa-comments" style="font-size: 2em"></span>
            {% else %}
                <span class="fa fa-comments-o" style="font-size: 2em"></span>
            {% endif %}

            </td>

            <td valign="top">
                <strong><a href="{{ forum.url }}">{{ forum.title }}</a></strong>

                <div class="forum-description">
                    {% autoescape false %}
                    {{ forum.description|markup }}
                    {% endautoescape %}
                </div>
            </td>

            <td valign="top" align="center" style="white-space: nowrap">{{ forum.topic_count }}</td>
            <td valign="top" align="center" style="white-space: nowrap">{{ forum.post_count }}</td>

            <td valign="top" align="right" style="white-space: nowrap">
                {% if forum.last_post_id %}
                <a href="{{ forum.last_post_url }}" title="{{ forum.last_post_title }}">
                    <strong>{{ forum.last_post_title|crop_title }}</strong>
                </a>
                <br />
                {{ forum.last_post_created|time_since }}<br />

                    by
                    {% if forum.last_post_user_id %}
                    <a href="#">{{ forum.last_post_username }}</a>
                    {% else %}
                    {{ forum.last_post_username }}
                    {% endif %}

                {% else %}
                No posts.
                {% endif %}
            {% endif %}
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>

openspending/templates/forum/forum/forum.html
{% set page_title = forum.title %}
{% set active_forum_nav=True %}

{% extends "forum/layout.html" %}
{% block forumcontent %}
{% from 'forum/macros.html' import render_pagination, topic_pages %}

<ol class="breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">Forum</a></li>
    <li><a href="{{ forum.category.url }}">{{ forum.category.title }}</a></li>
    <li class="active">{{ forum.title }}</li>
</ol>

<div class="pull-left">
    {{ render_pagination(topics, forum.url) }}
</div> <!-- end span pagination -->

{% if current_user|post_topic(forum) %}
<div class="pull-right">

    {% if forum.locked %}
    <span class="btn btn-primary">
        <span class="fa fa-lock"></span> Locked
    </span>
    {% else %}
    <a href="{{ url_for('forum.new_topic', forum_id=forum.id, slug=forum.slug) }}" class="btn btn-primary">
        <span class="fa fa-pencil"></span> New Topic
    </a>
    {% endif %}
</div>
{% endif %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th colspan="5">
                {{ forum.title }}
            </th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="2">Topic</td>

            <td>Posts</td>

            <td>Views</td>

            <td>Last Post</td>
        </tr>

        {% for topic, topicread in topics.items %}
        <tr>
            <td class="topic-status" width="4%" style="vertical-align: middle; text-align: center;">
            {% if topic.locked %}
                <span class="fa fa-lock" style="font-size: 2em"></span>
            {% elif topic.important %}
                {% if topic|topic_is_unread(topicread, current_user, forumsread) %}
                    <span class="fa fa-star" style="font-size: 2em"></span>
                {% else %}
                    <span class="fa fa-star-o" style="font-size: 2em"></span>
                {% endif %}
            {% else %}
                {% if topic|topic_is_unread(topicread, current_user, forumsread) %}
                    <span class="fa fa-comment" style="font-size: 2em"></span>
                {% else %}
                    <span class="fa fa-comment-o" style="font-size: 2em"></span>
                {% endif %}
            {% endif %}

            </td>
            <td>
                <div>
                    <a href="{{ topic.url }}">{{ topic.title }}</a>
                    <!-- Topic Pagination -->
                    {{ topic_pages(topic, flaskbb_config["POSTS_PER_PAGE"]) }}
                    <br />
                    <small>
                        by
                        {% if topic.user_id %}
                         <a href="{{ topic.user.url }}">{{ topic.user.username }}</a>
                        {% else %}
                        {{ topic.username }}
                        {% endif %}
                    </small>
                </div>
            </td>
            <td>
                {{ topic.post_count }}
            </td>
            <td>
                {{ topic.views }}
            </td>
            <td>
                <a href="{{ topic.last_post.url }}">{{ topic.last_post.date_created }}</a><br />

                <small>
                    by
                    {% if topic.last_post.user_id %}
                    <a href="{{ topic.last_post.user.url }}">{{ topic.last_post.user.username }}</a>
                    {% else %}
                    {{ topic.last_post.username }}
                    {% endif %}
                </small>
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="5">
                No Topics.
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>

<div class="pull-left">
    <a class="btn btn-default" href="{{ url_for('forum.manage_forum', forum_id=forum.id, slug=forum.slug) }}">
        <span class="fa fa-tasks"></span> Moderation Mode
    </a>
</div>
{% endblock %}

openspending/templates/forum/forum/topic.html
{% extends "forum/layout.html" %}
{% set page_title = "%s - Topic"%topic.title %}
{% set active_forum_nav=True %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='forumstatic/css/bootstrap-markdown.min.css') }}">
{% endblock %}

{% block forumcontent %}
{% from 'forum/macros.html' import render_pagination, form_field %}

<ol class="breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">Forum</a></li>
    <li><a href="{{ topic.forum.category.url }}">{{ topic.forum.category.title }}</a></li>
    <li><a href="{{ topic.forum.url }}">{{ topic.forum.title }}</a></li>
    <li class="active">{{ topic.title }}</li>
</ol>

{% include 'forum/forum/topic_controls.html' %}

<table class="table table-bordered">
    <tbody>
        {% for post, user in posts.items %}
        <tr>
            <td >
                <span class="pull-right">
                    <strong>#{%- if posts.page == 1 -%} {{ loop.index }} {%- else -%} {{ loop.index + (posts.page - 1) * flaskbb_config["POSTS_PER_PAGE"] }} {%- endif -%}</strong>
                </span>
                <span class="pull-left">
                    <a href="
                    {%- if posts.page > 1 -%}
                        {{ topic.url }}?page={{ posts.page }}#pid{{ post.id }}
                    {%- else -%}
                        {{ topic.url }}#pid{{ post.id }}
                    {%- endif -%}
                        ">{{ post.date_created|format_date('%d %B %Y') }}</a>
                </span>
            </td>
        </tr>

        <tr>
        <td>
            <table class="table table-borderless">
                <tr>
                {% if post.user_id %}
                    {% if user.avatar %}
                    <td width="1">
                        <img src="{{ user.avatar }}" alt="Avatar" height="100" width="100">
                    </td>
                    {% endif %}
                    <td>
                        <a href="{{ user.url }}">
                            <span style="font-weight:bold">{{ user.username }}</span> <!-- TODO: Implement userstyles -->
                        </a>
                    </td>

                    <td class="pull-right">
                        Posts: {{ user.post_count }}<br />
                    </td>
                {% else %}
                    <td>
                        <strong>{{ post.username }}</strong>
                        <br />
                        Guest
                    </td>
                {% endif %}
                </tr>
            </table>
        </td>
        </tr>

        <tr>
            <td>
                <div class="post_body" id="pid{{ post.id }}">
                {% autoescape false %}
                    {{ post.content|markup }}
                {% endautoescape %}
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <span class="pull-left">
                    {% if user.website %}
                    {% if current_user|is_authenticated %}| {% endif %}<a href="{{ user.website }}">Website</a>
                    {% endif %}
                </span>

                <span class="pull-right">
                    {% if current_user|is_authenticated %}
                    <a href="{{ url_for('forum.report_post', post_id=post.id) }}" onclick="window.open(this.href, 'wio_window','width=500,height=500'); return false;">
                        Report
                    </a> |
                    {% endif %}
                    {% if current_user|edit_post(post) %}
                    <a href="{{ url_for('forum.edit_post', post_id=post.id) }}">Edit</a> |
                    {% endif %}
                    {% if topic.first_post_id == post.id %}
                        {% if current_user|delete_topic(topic) %}
                        <form class="inline-form" method="post" action="{{ url_for('forum.delete_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">Delete</button> |
                        </form>
                        {% endif %}
                    {% else %}
                        {% if current_user|delete_post(post) %}
                        <form class="inline-form" method="post" action="{{ url_for('forum.delete_post', post_id=post.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">Delete</button> |
                        </form>
                        {% endif %}
                    {% endif %}
                </span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% include 'forum/forum/topic_controls.html' %}

{% if form %}
    {% from "forum/macros.html" import render_field, render_submit_field %}
    <form class="form" action="#" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />


        {{ render_field(form.content, div_class="col-sm-12 reply-content", rows="10", placeholder="", **{'data-provide': 'markdown', 'data-autofocus': 'true', 'id': 'quickreply-editor'}) }}

        <div class="col-sm-12" style="padding-top: 5px">
        {{ render_submit_field(form.submit) }}
        </div>
    </form>
{% endif %}

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='forumstatic/js/marked.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='forumstatic/js/bootstrap-markdown.js') }}"></script>
{% endblock %}

openspending/templates/forum/forum/topic_controls.html
<div class="pull-left">
    {{ render_pagination(posts, topic.url) }}
</div> <!-- end span pagination -->

{% if current_user|is_authenticated %}
    <div class="pull-right" style="padding-left: 15px">
        {% if current_user.is_tracking_topic(topic) %}
        <form class="inline-form" method="post" action="{{ url_for('forum.untrack_topic', topic_id=topic.id, slug=topic.slug) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="btn btn-default">
                <span class="fa fa-tag" aria-hidden="true"></span> Untrack Topic
            </button>
        </form>
        {% else %}
        <form class="inline-form" method="post" action="{{ url_for('forum.track_topic', topic_id=topic.id, slug=topic.slug) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="btn btn-default">
                <span class="fa fa-tag" aria-hidden="true"></span> Track Topic
            </button>
        </form>
        {% endif %}

        {% if current_user|post_reply(topic) %}
        <a href="{{ url_for('forum.new_post', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-primary">
            <span class="fa fa-pencil"></span> Reply
        </a>
        {% endif %}
    </div>
{% endif %}

<div class="pull-right">
{% if current_user|delete_topic(topic) %}
    <form class="inline-form" method="post" action="{{ url_for('forum.delete_topic', topic_id=topic.id, slug=topic.slug) }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button class="btn btn-danger">
            <span class="fa fa-trash-o"></span> Delete Topic
        </button>
    </form>
{% endif %}
{% if current_user|can_moderate %}
    {% if not topic.locked %}
        <form class="inline-form" method="post" action="{{ url_for('forum.lock_topic', topic_id=topic.id, slug=topic.slug) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="btn btn-warning">
                <span class="fa fa-lock"></span> Lock Topic
            </button>
        </form>
    {% else %}
        <form class="inline-form" method="post" action="{{ url_for('forum.unlock_topic', topic_id=topic.id, slug=topic.slug) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="btn btn-warning">
                <span class="fa fa-unlock"></span> Unlock Topic
            </button>
        </form>
    {% endif %}

    {% if not topic.important %}
        <form class="inline-form" method="post" action="{{ url_for('forum.highlight_topic', topic_id=topic.id, slug=topic.slug) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="btn btn-success">
                <span class="fa fa-star"></span> Highlight Topic
            </button>
        </form>
    {% else %}
        <form class="inline-form" method="post" action="{{ url_for('forum.trivialize_topic', topic_id=topic.id, slug=topic.slug) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="btn btn-success">
                <span class="fa fa-star-o"></span> Trivialize Topic
            </button>
        </form>
    {% endif %}
{% endif %}
</div>

<div class="clearfix"></div>