openspending/forum/forum/forms.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.forms
    ~~~~~~~~~~~~~~~~~~~~

    It provides the forms that are needed for the forum views.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask_wtf import Form
from wtforms import (TextAreaField, StringField, SelectMultipleField,
                     BooleanField, SubmitField)
from wtforms.validators import DataRequired, Optional, Length
from flask_babelex import lazy_gettext as _

from openspending.forum.forum.models import Topic, Post, Report, Forum
from openspending.model.account import Account as User


class QuickreplyForm(Form):
    content = TextAreaField(_("Quick Reply"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    submit = SubmitField(_("Reply"))

    def save(self, user, topic):
        post = Post(content=self.content.data)
        return post.save(user=user, topic=topic)


class ReplyForm(Form):
    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this Topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Reply"))
    preview = SubmitField(_("Preview"))

    def save(self, user, topic):
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return post.save(user=user, topic=topic)


class NewTopicForm(ReplyForm):
    title = StringField(_("Topic Title"), validators=[
        DataRequired(message=_("Please choose a Topic Title."))])

    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this Topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Post Topic"))
    preview = SubmitField(_("Preview"))

    def save(self, user, forum):
        topic = Topic(title=self.title.data)
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return topic.save(user=user, forum=forum, post=post)


class ReportForm(Form):
    reason = TextAreaField(_("Reason"), validators=[
        DataRequired(message=_("What's the reason for reporting this post?"))
    ])

    submit = SubmitField(_("Report Post"))

    def save(self, user, post):
        report = Report(reason=self.reason.data)
        return report.save(post=post, user=user)


# class UserSearchForm(Form):
#     search_query = StringField(_("Search"), validators=[
#         Optional(), Length(min=3, max=50)
#     ])

#     submit = SubmitField(_("Search"))

#     def get_results(self):
#         query = self.search_query.data
#         return User.query.whoosh_search(query)


class SearchPageForm(Form):
    search_query = StringField(_("Searh Terms"), validators=[
        DataRequired(), Length(min=3, max=50)])

    search_types = SelectMultipleField(_("Content"), validators=[
        DataRequired()], choices=[('post', _('Post')), ('topic', _('Topic')),
                                  ('forum', _('Forum'))])

    submit = SubmitField(_("Search"))

    def get_results(self):
        # Because the DB is not yet initialized when this form is loaded,
        # the query objects cannot be instantiated in the class itself
        search_actions = {
            'post': Post.query.whoosh_search,
            'topic': Topic.query.whoosh_search,
            'forum': Forum.query.whoosh_search,
        }

        query = self.search_query.data
        types = self.search_types.data
        results = {}

        for search_type in search_actions.keys():
            if search_type in types:
                results[search_type] = search_actions[search_type](query)

        return results

openspending/forum/forum/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.views
    ~~~~~~~~~~~~~~~~~~~~

    This module handles the forum logic like creating and viewing
    topics and posts.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import datetime

from flask import (Blueprint, redirect, url_for, current_app,
                   request, flash, jsonify, render_template)
from flask_login import login_required, current_user
from flask_babelex import gettext as _

from openspending.core import db
from openspending.forum.utils.forum_settings import flaskbb_config
from openspending.forum.utils.helpers import (get_online_users, time_diff, format_quote,
                                   do_topic_action)
from openspending.auth.perms import (can_post_reply, can_post_topic,
                                       can_delete_topic, can_delete_post,
                                       can_edit_post, can_moderate)
from openspending.auth import authenticated_required
from openspending.forum.forum.models import (Category, Forum, Topic, Post, ForumsRead,
                                  TopicsRead)
from openspending.forum.forum.forms import (QuickreplyForm, ReplyForm, NewTopicForm,
                                 ReportForm, SearchPageForm)
from openspending.model.account import Account as User

forum = Blueprint("forum", __name__)


@forum.route("/")
@authenticated_required
def index():
    categories = Category.get_all(user=current_user)

    # Fetch a few stats about the forum
    user_count = User.query.count()
    topic_count = Topic.query.count()
    post_count = Post.query.count()
    newest_user = User.query.order_by(User.id.desc()).first()


    # online_users = len(get_online_users())
    # online_guests = len(get_online_users(guest=True))

    return render_template("forum/forum/index.html",
                           categories=categories,
                           user_count=user_count,
                           topic_count=topic_count,
                           post_count=post_count,
                           newest_user=newest_user)
                           # online_users=online_users,
                           # online_guests=online_guests)


@forum.route("/category/<int:category_id>")
@forum.route("/category/<int:category_id>-<slug>")
@authenticated_required
def view_category(category_id, slug=None):
    return redirect(url_for("forum.index"))
    # category, forums = Category.\
    #     get_forums(category_id=category_id, user=current_user)

    # return render_template("forum/forum/category.html", forums=forums,
    #                        category=category)


@forum.route("/forum/<int:forum_id>")
@forum.route("/forum/<int:forum_id>-<slug>")
def view_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id,
                                                 user=current_user)

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(
        forum_id=forum_instance.id, user=current_user, page=page,
        per_page=flaskbb_config["TOPICS_PER_PAGE"])

    return render_template(
        "forum/forum/forum.html", forum=forum_instance,
        topics=topics, forumsread=forumsread,
        flaskbb_config=flaskbb_config
    )


@forum.route("/topic/<int:topic_id>", methods=["POST", "GET"])
@forum.route("/topic/<int:topic_id>-<slug>", methods=["POST", "GET"])
def view_topic(topic_id, slug=None):
    page = request.args.get('page', 1, type=int)

    # Fetch some information about the topic
    topic = Topic.get_topic(topic_id=topic_id, user=current_user)

    # Count the topic views
    topic.views += 1
    topic.save()

    # fetch the posts in the topic
    posts = Post.query.\
        join(User, Post.user_id == User.id).\
        filter(Post.topic_id == topic.id).\
        add_entity(User).\
        order_by(Post.id.asc()).\
        paginate(page, flaskbb_config['POSTS_PER_PAGE'], False)

    # Update the topicsread status if the user hasn't read it
    forumsread = None
    if current_user.is_authenticated():
        forumsread = ForumsRead.query.\
            filter_by(user_id=current_user.id,
                      forum_id=topic.forum.id).first()

    topic.update_read(current_user, topic.forum, forumsread)

    form = None
    if can_post_reply(user=current_user, topic=topic):
        form = QuickreplyForm()
        if form.validate_on_submit():
            post = form.save(current_user, topic)
            return view_post(post.id)
    return render_template("forum/forum/topic.html", topic=topic, posts=posts,
                           last_seen=time_diff(), form=form)


@forum.route("/post/<int:post_id>")
def view_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    count = post.topic.post_count
    page = count / flaskbb_config["POSTS_PER_PAGE"]

    if count > flaskbb_config["POSTS_PER_PAGE"]:
        page += 1
    else:
        page = 1

    return redirect(post.topic.url + "?page=%d#pid%s" % (page, post.id))


@forum.route("/<int:forum_id>/topic/new", methods=["POST", "GET"])
@forum.route("/<int:forum_id>-<slug>/topic/new", methods=["POST", "GET"])
@login_required
def new_topic(forum_id, slug=None):
    forum_instance = Forum.query.filter_by(id=forum_id).first_or_404()

    if not can_post_topic(user=current_user, forum=forum_instance):
        flash(_("You do not have the permissions to create a new topic."),
              "danger")
        return redirect(forum.url)

    form = NewTopicForm()
    if request.method == "POST":
        if "preview" in request.form and form.validate():
            return render_template(
                "forum/forum/new_topic.html", forum=forum_instance,
                form=form, preview=form.content.data
            )
        if "submit" in request.form and form.validate():
            topic = form.save(current_user, forum_instance)
            # redirect to the new topic
            return redirect(url_for('forum.view_topic', topic_id=topic.id))

    return render_template(
        "forum/forum/new_topic.html", forum=forum_instance, form=form
    )


@forum.route("/topic/<int:topic_id>/delete", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/delete", methods=["POST"])
@login_required
def delete_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_delete_topic(user=current_user, topic=topic):
        flash(_("You do not have the permissions to delete this topic."),
              "danger")
        return redirect(topic.forum.url)

    involved_users = User.query.filter(Post.topic_id == topic.id,
                                       User.id == Post.user_id).all()
    topic.delete(users=involved_users)
    return redirect(url_for("forum.view_forum", forum_id=topic.forum_id))


@forum.route("/topic/<int:topic_id>/lock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/lock", methods=["POST"])
@login_required
def lock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to lock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/unlock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/unlock", methods=["POST"])
@login_required
def unlock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to unlock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = False
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/highlight", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/highlight", methods=["POST"])
@login_required
def highlight_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to highlight this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/trivialize", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/trivialize", methods=["POST"])
@login_required
def trivialize_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # Unlock is basically the same as lock
    if not can_moderate(user=current_user, forum=topic.forum):
        flash(_("You do not have the permissions to trivialize this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = False
    topic.save()
    return redirect(topic.url)


@forum.route("/forum/<int:forum_id>/edit", methods=["POST", "GET"])
@forum.route("/forum/<int:forum_id>-<slug>/edit", methods=["POST", "GET"])
@login_required
def manage_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id,
                                                 user=current_user)

    # remove the current forum from the select field (move).
    available_forums = Forum.query.order_by(Forum.position).all()
    available_forums.remove(forum_instance)

    if not can_moderate(current_user, forum=forum_instance):
        flash(_("You do not have the permissions to moderate this forum."),
              "danger")
        return redirect(forum_instance.url)

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(

openspending/templates/forum/management/banned_users.html
{% set page_title = "Banned Users" %}
{% set active_management_user_nav=True %}

{% extends "forum/management/management_layout.html" %}
{% block management_content %}
{% from 'forum/macros.html' import render_pagination, render_field, group_field, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.users', "Manage Users") }}
        {{ navlink('management.banned_users', 'Banned Users') }}

        {% if current_user|is_admin %}
            {{ navlink('management.add_user', "Add User") }}
        {% endif %}
    </ul>
</div><!--/.col-md-3 -->

<div class="col-md-9">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">

                    <span class="fa fa-user-times"></span> Banned Users

                    <div class="pull-right action-buttons">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default btn-xs" onclick="return show_management_search()">
                                <span class="fa fa-search" style="margin-right: 0px;"></span> Search
                            </button>
                        </div>
                    </div>

                </div>
                <div class="panel-body management-body">


                    <form class="search-form" role="form" method="post">
                        {{ search_form.hidden_tag() }}
                        <div class="input-group">
                            {{ group_field(search_form.search_query, css_class="form-control") }}
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button"><span class="fa fa-search"></span></button>
                            </span>
                        </div>
                    </form>
                </div>

                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th><input type="checkbox" name="rowtoggle" class="action-checkall" title="Select All"/></th>
                                <th>#</th>
                                <th>Username</th>
                                <th>Posts</th>
                                <th>Date registered</th>
                                <th>Group</th>
                                <th>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                            <span class="fa fa-cog" style="margin-right: 0px;"></span> Actions
                                        </button>
                                        <ul class="dropdown-menu slidedown">
                                            <li>
                                                <a href="javascript:void(0)" onclick="return bulk_actions.execute('{{ url_for('management.unban_user') }}', 'Are you sure you want to unban these Users?')">
                                                    <span class="fa fa-flag text-success"></span> Unban selected Users
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user in users.items %}
                            <tr class="action-row">
                                <td><input type="checkbox" name="rowid" class="action-checkbox" value="{{ user.id }}" title="Select User"/></td>
                                <td>{{ user.id }}</td>
                                <td><a href="{{ url_for('user.profile', username=user.username) }}">{{ user.username }}</a></td>
                                <td>{{ user.post_count }}</td>
                                <td>{{ user.date_joined|format_date('%b %d %Y') }}</td>
                                <td>
                                    {% if current_user|can_ban_user and user.permissions['banned'] %}
                                        <form class="inline-form" id="unban-{{user.id}}" method="post" action="{{ url_for('management.unban_user', user_id = user.id) }}">
                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

                                            <button class="btn btn-link">
                                                <span class="fa fa-flag text-success" data-toggle="tooltip" data-placement="top" title="Unban"></span>
                                            </button>
                                        </form>
                                    {% endif %}
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="6">
                                    No users found matching your search criteria.
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            {{ render_pagination(users, url_for('management.users')) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
    var bulk_actions = new BulkActions();

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    </script>
{% endblock %}

openspending/templates/forum/management/forums.html
{% set page_title = "Forums" %}

{% extends "forum/management/management_layout.html" %}
{% block management_content %}
{% from 'forum/macros.html' import render_pagination, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.forums', "Manage Forums") }}
        {{ navlink('management.add_forum', "Add Forum") }}
        {{ navlink('management.add_category', "Add Category") }}
    </ul>
</div>

 <div class="col-md-9">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class="fa fa-comments"></span> Manage Forums
                </div>
                <div class="panel-body">
                    {% for category in categories %}
                    <table class="table table-bordered">
                        <thead class="categoryhead">
                            <tr>
                                <td colspan="2">
                                    <div><strong><a href="{{ url_for('forum.view_category', category_id=category.id) }}">{{ category.title }}</a></strong></div>
                                </td>
                                <td valign="top" align="center" style="white-space: nowrap">
                                    <a href="{{ url_for('management.add_forum', category_id=category.id) }}">Add Forum</a> |
                                    <a href="{{ url_for('management.edit_category', category_id = category.id) }}">Edit</a> |
                                    <form class="inline-form" method="post" action="{{ url_for('management.delete_category', category_id=category.id) }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                                        <button class="btn btn-link">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        </thead>
                        <tbody class="forumbody">
                            <tr class="forum_stats">
                                <td colspan="2"><strong>Forum</strong></td>
                                <td width="85" align="center" style="white-space: nowrap"><strong>Management</strong></td>
                            </tr>

                            {% for forum in category.forums %}
                            <tr>
                                <td align="center" valign="center" width="4%">

                                </td>

                                <td valign="top">
                                    <strong><a href="{{ url_for('forum.view_forum', forum_id=forum.id) }}">{{ forum.title }}</a></strong>

                                    <div class="forum-description">
                                        {% autoescape false %}
                                        {{ forum.description|markup }}
                                        {% endautoescape %}
                                    </div>
                                </td>

                                <td valign="top" align="center" style="white-space: nowrap">
                                    <a href="{{ url_for('management.edit_forum', forum_id = forum.id) }}">Edit</a> |
                                    <form class="inline-form" method="post" action="{{ url_for('management.delete_forum', forum_id=forum.id) }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                                        <button class="btn btn-link">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

openspending/templates/forum/management/reports.html
{% set page_title = "Reports" %}
{% set active_management_report_nav=True %}

{% extends "forum/management/management_layout.html" %}
{% block management_content %}
{% from 'forum/macros.html' import render_pagination, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.unread_reports', "Show unread reports") }}
        {{ navlink('management.reports', "Show all reports") }}
    </ul>
</div>

<div class="col-md-9">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class="fa fa-flag"></span> All Reports
                </div>
                <div class="panel-body management-body"></div>

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Poster</th>
                            <th>Topic</th>
                            <th>Reporter</th>
                            <th>Reason</th>
                            <th>Reported</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for report in reports.items %}
                        <tr>
                            <td>{{ report.id }}</td>
                            <td>{{ report.post.user.username }}</td>
                            <td><a href="{{ url_for('forum.view_post', post_id=report.post.id) }}" target="_blank">{{ report.post.topic.title }}</a></td>
                            <td>{{ report.reporter.username }}</td>
                            <td>{{ report.reason }}</td>
                            <td>{{ report.reported|time_since }}</td>
                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="6">No reports.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            {{ render_pagination(reports, url_for('management.reports')) }}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

openspending/templates/forum/management/unread_reports.html
{% set page_title = "Unread Reports" %}
{% set active_management_report_nav=True %}

{% extends "forum/management/management_layout.html" %}
{% block management_content %}
{% from 'forum/macros.html' import render_pagination, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.unread_reports', "Show unread reports") }}
        {{ navlink('management.reports', "Show all reports") }}
    </ul>
</div>

<div class="col-md-9">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class="fa fa-flag"></span> Unread Reports
                </div>
                <div class="panel-body management-body"></div>

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="rowtoggle" class="action-checkall" title="Select All"/></th>
                            <th>#</th>
                            <th>Poster</th>
                            <th>Topic</th>
                            <th>Reporter</th>
                            <th>Reason</th>
                            <th>Reported</th>
                            <th>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        <span class="fa fa-cog" style="margin-right: 0px;"></span> Actions
                                    </button>
                                    <ul class="dropdown-menu slidedown">
                                        <li>
                                            <a href="javascript:void(0)" onclick="return bulk_actions.execute('{{ url_for('management.report_markread') }}', 'Are you sure you want to mark these Reports as read?')">
                                                <span class="fa fa-flag-o text-primary"></span> Mark as Read
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for report in reports.items %}
                        <tr class="action-row">
                            <td><input type="checkbox" name="rowid" class="action-checkbox" value="{{ report.id }}" title="Select Report"/></td>
                            <td>{{ report.id }}</td>
                            <td>{{ report.post.user.username }}</td>
                            <td><a href="{{ url_for('forum.view_post', post_id=report.post.id) }}" target="_blank">{{ report.post.topic.title }}</a></td>
                            <td>{{ report.reporter.username }}</td>
                            <td>{{ report.reason }}</td>
                            <td>{{ report.reported|time_since }}</td>
                            <td>
                                <form class="inline-form" id="read-{{report.id}}" method="post" action="{{ url_for('management.report_markread', report_id=report.id) }}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                                    <button class="btn btn-link">
                                        <span class="fa fa-flag-o text-primary" data-toggle="tooltip" data-placement="top" title="Mark as Read"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="7">No unread reports.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            {{ render_pagination(reports, url_for('management.unread_reports')) }}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
    var bulk_actions = new BulkActions();

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    </script>
{% endblock %}