openspending/forum/forum/forms.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.forms
    ~~~~~~~~~~~~~~~~~~~~

    It provides the forms that are needed for the forum views.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask_wtf import Form
from wtforms import (TextAreaField, StringField, SelectMultipleField,
                     BooleanField, SubmitField)
from wtforms.validators import DataRequired, Optional, Length
from flask_babelex import lazy_gettext as _

from openspending.forum.forum.models import Topic, Post, Report, Forum
from openspending.model.account import Account as User


class QuickreplyForm(Form):
    content = TextAreaField(_("Quick Reply"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    submit = SubmitField(_("Reply"))

    def save(self, user, topic):
        post = Post(content=self.content.data)
        return post.save(user=user, topic=topic)


class ReplyForm(Form):
    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this Topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Reply"))
    preview = SubmitField(_("Preview"))

    def save(self, user, topic):
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return post.save(user=user, topic=topic)


class NewTopicForm(ReplyForm):
    title = StringField(_("Topic Title"), validators=[
        DataRequired(message=_("Please choose a Topic Title."))])

    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this Topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Post Topic"))
    preview = SubmitField(_("Preview"))

    def save(self, user, forum):
        topic = Topic(title=self.title.data)
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return topic.save(user=user, forum=forum, post=post)


class ReportForm(Form):
    reason = TextAreaField(_("Reason"), validators=[
        DataRequired(message=_("What's the reason for reporting this post?"))
    ])

    submit = SubmitField(_("Report Post"))

    def save(self, user, post):
        report = Report(reason=self.reason.data)
        return report.save(post=post, user=user)


# class UserSearchForm(Form):
#     search_query = StringField(_("Search"), validators=[
#         Optional(), Length(min=3, max=50)
#     ])

#     submit = SubmitField(_("Search"))

#     def get_results(self):
#         query = self.search_query.data
#         return User.query.whoosh_search(query)


class SearchPageForm(Form):
    search_query = StringField(_("Searh Terms"), validators=[
        DataRequired(), Length(min=3, max=50)])

    search_types = SelectMultipleField(_("Content"), validators=[
        DataRequired()], choices=[('post', _('Post')), ('topic', _('Topic')),
                                  ('forum', _('Forum'))])

    submit = SubmitField(_("Search"))

    def get_results(self):
        # Because the DB is not yet initialized when this form is loaded,
        # the query objects cannot be instantiated in the class itself
        search_actions = {
            'post': Post.query.whoosh_search,
            'topic': Topic.query.whoosh_search,
            'forum': Forum.query.whoosh_search,
        }

        query = self.search_query.data
        types = self.search_types.data
        results = {}

        for search_type in search_actions.keys():
            if search_type in types:
                results[search_type] = search_actions[search_type](query)

        return results

openspending/views/account.py
import colander
from flask import Blueprint, render_template, request, redirect, abort
from flask.ext.login import current_user, login_user, logout_user
from flask import current_app
from werkzeug.security import check_password_hash, generate_password_hash

from openspending.core import db, login_manager

from openspending.model.account import (Account, AccountRegister,
                                        AccountSettings)
from openspending.lib.helpers import url_for, obj_or_404
from openspending.lib.helpers import flash_notice, flash_success, flash_error
from openspending.lib.reghelper import sendhash, send_reset_hash
from openspending.views.context import generate_csrf_token
from openspending.auth.perms import is_authenticated

from openspending.model import Dataview


from wtforms import Form, TextField, PasswordField, validators



blueprint = Blueprint('account', __name__)


@login_manager.request_loader
def load_user_from_request(request):
    api_key = request.args.get('api_key')
    if api_key and len(api_key):
        account = Account.by_api_key(api_key)
        if account:
            return account

    api_key = request.headers.get('Authorization')
    if api_key and len(api_key) and ' ' in api_key:
        method, api_key = api_key.split(' ', 1)
        if method.lower() == 'apikey':
            account = Account.by_api_key(api_key)
            if account:
                return account
    return None


@blueprint.route('/login', methods=['GET'])
def login():
    """ Render the login/registration page. """
    if request.form.get("csrf_token",None):
        values = {"csrf_token": request.form.get('csrf_token')}
    else:
        values = {"csrf_token": generate_csrf_token()}

    if request.args.get("next", None):
        values['next'] =  request.args.get("next", None)

    return render_template('account/login.jade', 
                        form_fill=values,
                        form_fill_login=values)


@blueprint.route('/login', methods=['POST', 'PUT'])
def login_perform():
    account = Account.by_email(request.form.get('login'))
    if account is not None and not account.verified:
        return redirect(url_for('account.email_message', id=account.id))
    #if account is not None and account.verified == True:
    if account is not None:
        if check_password_hash(account.password, request.form.get('password')):
            logout_user()
            login_user(account, remember=True)
            flash_success("Welcome back, " + account.fullname + "!")
            if request.form.get("next", None):
                return redirect(request.form.get("next"))
            else:
                return redirect(url_for('home.index'))
    flash_error("Incorrect user name or password!")
    return login()


@blueprint.route('/register', methods=['POST', 'PUT'])
def register():
    """ Perform registration of a new user """
    errors, values = {}, dict(request.form.items())

    try:
        # Grab the actual data and validate it
        data = AccountRegister().deserialize(values)

        #check if email is already registered
            # it is, then send the email hash for the login

        #check that email is real
        #get the domain
        if (data['email'].find('@') == -1 or data['email'].find('.') == -1):
            flash_error("You must use a valid USG email address")
            raise colander.Invalid(AccountRegister.email,
                    "You must use a valid USG email address")

        domain = data['email'][data['email'].find('@') + 1:]

        if 'EMAIL_WHITELIST' not in current_app.config.keys():
            flash_error("Your email is not current supported.  The login option is only available for US Government offices at this time.")
            raise colander.Invalid(AccountRegister.email,
                "System not set correctly.  Please contact the administrator.")

        domainvalid = False

        for domainemail in current_app.config['EMAIL_WHITELIST']:
            if domain.lower() == domainemail.lower():
                domainvalid = True

        if not domainvalid:
            flash_error("Your email is not current supported.  The login option is only available for US Government offices at this time.")
            raise colander.Invalid(AccountRegister.email,
                "Your email is not available for registration.  Currently it is only available for US Government emails.")



        # Check if the username already exists, return an error if so
        if Account.by_email(data['email']):
            flash_error("Login Name already exists.  Click request password reset to change your password.")

            #resend the hash here to the email and notify the user
            raise colander.Invalid(
                AccountRegister.email,
                "Login Name already exists.  Click request password reset to change your password.")



        # Create the account
        account = Account()
        account.fullname = data['fullname']
        account.email = data['email']
        

        db.session.add(account)
        db.session.commit()

        # Perform a login for the user
        #login_user(account, remember=True)

        sendhash(account)


        # TO DO redirect to email sent page
        return redirect(url_for('account.email_message', id=account.id))
    except colander.Invalid as i:
        errors = i.asdict()
    if request.form.get("csrf_token",None):
        values['csrf_token'] = request.form.get('csrf_token')
    else:
        values["csrf_token"] = generate_csrf_token()
    return render_template('account/login.jade', form_fill=values,
                           form_errors=errors,
                           form_fill_login={'csrf_token': values['csrf_token']})


@blueprint.route('/account/verify', methods=['POST', 'GET'])
def verify():


    if request.method == 'GET':
        loginhash = request.args.get('login')
        if not loginhash:
            message = "Invalid URL.  Please contact system administrator."
            return render_template('account/message.jade', message=message)


        account = Account.by_login_hash(loginhash)

        if not account:
            message = "This URL is no longer valid.  If you have an account, you can reset your password at the " + \
                        " <a href='" + url_for('account.trigger_reset') + "'>password reset page</a>. Or you can register at \
                        <a href='" + url_for('account.login') + "'>login page</a>"
            return render_template('account/message.jade', message=message)

    
        #request.form.loginhash = {"data":loginhash}
        if request.form.get("csrf_token",None):
            values = {'loginhash': loginhash, 
                        "csrf_token": request.form.get('csrf_token')}
        else:
            values = {'loginhash': loginhash, 
                    "csrf_token": generate_csrf_token()}
        return render_template('account/verify.jade',
                account=account, 
                form_fill=values)

    else:
        loginhash = request.form.get('loginhash')
        if not loginhash:
            message = "We cannot find your unique URL"
            return render_template('account/message.jade', message=message)

        account = Account.by_login_hash(loginhash)

        if not account:
            message = "We could not find your account"
            return render_template('account/message.jade', message=message)

        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        # Check if passwords match, return error if not
        if password1 != password2:
            error = "Your passwords do not match"
            values = {'loginhash': loginhash, 
                        "csrf_token": request.form.get('csrf_token')}

            return render_template('account/verify.jade', 
                loginhash=loginhash, 
                account=account, 
                error=error,
                form_fill=values)

        account.password = generate_password_hash(password1)
        #reset that hash but don't send it.
        account.reset_loginhash()
        account.verified = True
        db.session.commit()


        flash_success("Password saved and you are now verified.  Thank you.")
        login_user(account, remember=True)





        return redirect(url_for('home.index'))




#Developemnt and beta only
@blueprint.route('/accounts/email_message', methods=['GET'])
def email_message():
    """
    Redirect user to this to tell them to go check their email
    """

    user_id = request.args.get('id')
    useraccount = Account.by_id(user_id)

    if not useraccount:
        message = "There is no user with this account"
        return render_template('account/email_message.jade', message=message)

    if useraccount.admin:
        message = "This operation is not possible for this user type"
        return render_template('account/email_message.jade', message=message)


    emailsplit = useraccount.email.split("@")
    email = emailsplit[0][:3] + "*****@" + emailsplit[1]

    flash_success("Your account is being set up.  Please see note below.")

    message = """Thank you for your request.  An email has been sent to %s with 
                further instructions.  If you have not recieved an email in next few minutes
                 please try <a style='color:#337ab7' href='%s'>resetting your
                 password</a>."""%(email, url_for('account.trigger_reset'))



    # message_dict = sendhash(useraccount, gettext=True)
    # message = str(message_dict) + "<br/><br/><a href='" + message_dict['verifylink'] + "'><h3>Click to Verify</h3></a>"

    return render_template('account/email_message.jade', 
                            message=message)





@blueprint.route('/logout')
def logout():
    logout_user()
    flash_success("You have been logged out.")
    return redirect(url_for('home.index'))




#TODO send a new hash to this user

openspending/templates/forum/flashed_messages.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                {% set icon = 'glyphicon glyphicon-exclamation-sign' %}
            {% elif category == 'success' %}
                {% set icon = 'glyphicon glyphicon-ok-sign' %}
            {% else %}
                {% set icon = 'glyphicon glyphicon-info-sign' %}
            {% endif %}
            <div class="alert alert-{{ category }}">
                <span class="{{ icon }}"></span>&nbsp;
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

openspending/templates/forum/layout.html
{% extends "base.jade" %}

{% block page_title %}FAQ{% endblock %}


{% block banner %}

{% endblock %}


{% block optional_head %}
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='forumstatic/css/font-awesome.min.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='forumstatic/css/pygments.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='forumstatic/css/flaskbb.css') }}">

    {% block css %}
    {% endblock %}

    {# for various extra things #}
    {% block head_extra %}
    {% endblock %}
{% endblock %}

{% block content %}

    <div class="container">

        {% block forumcontent %}
        {% endblock %}
    </div> <!-- /container -->

{% endblock %}

{% block footer_scripts %}
        <script src="{{ url_for('static', filename='forumstatic/js/flaskbb.js') }}"></script>
        {% block javascript %}

        {% endblock %}

        {% block scripts %}
        {% endblock %}
{% endblock %}

openspending/templates/forum/macros.html
{%- macro field_label(field) -%}
    <label for="{{ field.id }}">{{ field.label.text }}</label>
{% endmacro %}


{%- macro field_description(field) -%}
    {% if field.description %}
        <span class="help-block">{{ field.description|safe }}</span>
    {% endif %}
{%- endmacro -%}


{%- macro field_errors(field) -%}
    {% if field.errors %}
        {%- for error in field.errors -%}
        <span class="help-block">{{error}}</span>
        {%- endfor -%}
    {% endif %}
{%- endmacro -%}


{%- macro render_quickreply(field, rows, cols, div_class='') -%}
{%- if kwargs['required'] or field.flags.required -%}
    {% if div_class %}
        {{ field(class=div_class, required="required", cols=cols, rows=rows, placeholder=field.label.text, **kwargs) }}
    {% else %}
        {{ field(class="new-message", required="required", cols=cols, rows=row, placeholder=field.label.text, **kwargs) }}
    {% endif %}
{%- else -%}
    {% if div_class %}
        {{ field(class=div_class, cols=cols, rows=row, placeholder=field.label.text, **kwargs) }}
    {% else %}
        {{ field(class="new-message", cols=cols, rows=row, placeholder=field.label.text, **kwargs) }}
    {% endif %}
{%- endif -%}

{{ field_description(field) }}
{{ field_errors(field) }}
{%- endmacro -%}


{# Renders a non bootstrap input field #}
{%- macro render_input_field(field, div_class='', placeholder='') -%}
{%- if div_class -%}
    <div class="{{ div_class }}">
{%- endif -%}

{%- if placeholder -%}
    {% set field_placeholder = placeholder %}
{%- else -%}
    {% set field_placeholder = field.label.text %}
{%- endif -%}

{%- if kwargs['required'] or field.flags.required -%}
    {{ field(required="required", placeholder=field_placeholder) }}
{%- else -%}
    {{ field(placeholder=field_placeholder) }}
{% endif %}

{%- if div_class -%}
    </div>
{%- endif -%}

{{ field_description(field) }}
{{ field_errors(field) }}
{%- endmacro -%}


{%- macro render_boolean_field(field, inline=False) -%}
<div class="checkbox{% if inline %}inline{% endif %}{% if field.errors %}has-error{% endif %}">
    <label>
    {{ field(**kwargs) }}
    {{ field.label.text }}
    </label>
    {{ field_description(field) }}
    {{ field_errors(field) }}
</div>
{%- endmacro -%}


{%- macro render_select_field(field, div_class='', select_class="form-control") -%}
<div class="form-group">
    {% if div_class %}
    <div class="{{ div_class }}">
    {% else %}
    <div class="col-sm-5">
    {% endif %}
        <label>{{ field.label.text }}</label>
        {% if field.type == 'QuerySelectMultipleField' or field.type == 'SelectMultipleField' %}
            {{ field(multiple=True, class=select_class) }}
        {% else %}
            {{ field(class=select_class) }}
        {%- endif -%}

        {{ field_description(field) }}
        {{ field_errors(field) }}
    </div>
</div>
{%- endmacro -%}


{%- macro render_submit_field(field, div_class='', input_class='') -%}
{% if div_class %}
<div class="{{ div_class }}">
{% endif %}

    {{ field(class=input_class or 'btn btn-success') }}

{% if div_class %}
</div>
{% endif %}
{%- endmacro -%}


{%- macro render_field(field, with_label=True, div_class='', rows='') -%}
<div class="form-group{%- if field.errors %} has-error{%- endif %}">
    {% if div_class %}
    <div class="{{ div_class }}">
    {% else %}
    <div class="col-sm-5">
    {% endif %}

        {% if with_label %}
            <label>{{ field.label.text }}</label>
        {% endif %}

        {%- if kwargs['required'] or field.flags.required -%}
            {% if rows %}
                {{ field(class="form-control", required="required", rows=rows, placeholder=field.label.text, **kwargs) }}
            {% else %}
                {{ field(class="form-control", required="required", placeholder=field.label.text, **kwargs) }}
            {% endif %}
        {%- else -%}
            {% if rows %}
                {{ field(class="form-control", rows=rows, placeholder=field.label.text, **kwargs) }}
            {% else %}
                {{ field(class="form-control", placeholder=field.label.text, **kwargs) }}
            {% endif %}
        {%- endif -%}

        {{ field_description(field) }}
        {{ field_errors(field) }}
    </div>
</div>
{%- endmacro -%}


{%- macro inline_field(field, label_text='', label_class='') -%}
<div class="form-group {%- if field.errors %} has-error{%- endif %}">
    {{field.label(class="sr-only")}}

    <div class="col-sm-4">
    {%- if kwargs['required'] or field.flags.required -%}
        {% if label_text %}
            {{field(class='form-control', placeholder=label_text, required="required", **kwargs)}}
        {% else %}
            {{field(class='form-control', placeholder=field.label.text, required="required", **kwargs)}}
        {% endif %}
    {%- else -%}
        {% if label_text %}
            {{field(class='form-control', placeholder=label_text, **kwargs)}}
        {% else %}
            {{field(class='form-control', placeholder=field.label.text, **kwargs)}}
        {% endif %}
    {%- endif -%}
    {{ field_description(field) }}
    {{ field_errors(field) }}
    </div>
</div>
{%- endmacro -%}


{%- macro group_field(field, label_text='', label_class='', css_class='form-control form-grouped') -%}
    <div class="form-group {%- if field.errors %} has-error{%- endif %}" style="margin-bottom: 0px;">
        {{field.label(class="sr-only")}}

        {%- if kwargs['required'] or field.flags.required -%}
            {% if label_text %}
                {{field(class=css_class, placeholder=label_text, required="required", **kwargs)}}
            {% else %}
                {{field(class=css_class, placeholder=field.label.text, required="required", **kwargs)}}
            {% endif %}
        {%- else -%}
            {% if label_text %}
                {{field(class=css_class, placeholder=label_text, **kwargs)}}
            {% else %}
                {{field(class=css_class, placeholder=field.label.text, **kwargs)}}
            {% endif %}
        {%- endif -%}
        {{ field_description(field) }}
        {{ field_errors(field) }}
    </div>
{%- endmacro -%}


{%- macro horizontal_select_field(field, div_class='', label_class='', select_class="form-control", surrounded_div="col-sm-4") -%}
<div class="form-group row {%- if field.errors %} has-error{%- endif %}">
    {% if label_class %}
        {{ field.label(class=label_class) }}
    {% else %}
        {{ field.label(class="col-sm-3 control-label") }}
    {% endif %}

    {% if div_class %}
        <div class="{{ div_class }}">
    {% else %}
        <div class="col-sm-5">
    {% endif %}

        <div class="row">
        {% if field.type == 'QuerySelectMultipleField' or field.type == 'SelectMultipleField' %}
            {{ field(multiple=True, class=select_class, surrounded_div=surrounded_div) }}
        {% else %}
            {{ field(class=select_class, surrounded_div=surrounded_div) }}
        {%- endif -%}
        </div>
        {{ field_description(field) }}
        {{ field_errors(field) }}
    </div>
</div>
{%- endmacro -%}


{%- macro horizontal_boolean_field(field, div_class='') -%}
{%- if div_class %}
<div class="{{ div_class }}">
{%- else %}
<div class="col-sm-offset-3 col-sm-3">
{%- endif %}
    <div class="checkbox">
        {{ field(**kwargs) }}
        {{ field_label(field) }}
    </div>
</div>
{%- endmacro -%}


{%- macro horizontal_submit_field(field, div_class='', input_class='') -%}
{% if div_class %}
<div class="{{ div_class }}">
{% else %}
<div class="col-sm-offset-3 col-sm-9">
{% endif %}
    {{ field(class=input_class or 'btn btn-success') }}
</div>
{%- endmacro -%}


{%- macro horizontal_field(field, label_text='', label_class='', div_class='', input_class='') -%}
<div class="form-group row {%- if field.errors %} has-error{%- endif %}">

    {% if field.type == "BooleanField" or field.type == "SubmitField" %}
        {% if field.type == "BooleanField" %}
            {{ horizontal_boolean_field(field, div_class) }}
        {% else %}
            {{ horizontal_submit_field(field, div_class) }}
        {% endif %}
    {% else %}

        {% if label_class %}
            {{ field.label(class=label_class) }}
        {% else %}
            {{ field.label(class="col-sm-3 control-label") }}
        {% endif %}

        {% if div_class %}
            <div class="{{ div_class }}">
        {% else %}
            <div class="col-sm-4">
        {% endif %}

        {%- if kwargs['required'] or field.flags.required -%}
            {% if label_text %}
                {{ field(class='form-control', placeholder=label_text, required="required", **kwargs) }}
            {% else %}
                {{ field(class='form-control', placeholder=field.label.text, required="required", **kwargs) }}
            {% endif %}
        {%- else -%}
            {% if label_text %}
                {{ field(class='form-control', placeholder=label_text, **kwargs) }}
            {% else %}
                {{ field(class='form-control', placeholder=field.label.text, **kwargs) }}
            {% endif %}
        {%- endif -%}
    </div> <!-- end div_class -->
    {% endif %}

    {{ field_description(field) }}
    {{ field_errors(field) }}

</div> <!-- end form-group -->
{%- endmacro -%}


{% macro topnav(endpoint, name, icon='', id='', active=False) %}
<li {% if id %}id={{id}}{% endif %} {% if endpoint == request.endpoint or active == True %}class="active"{% endif %}>
    <a href={{ url_for(endpoint) }}>
        {% if icon %}<i class="{{ icon }}"></i> {% endif %}{{ name }}
    </a>
</li>
{% endmacro %}


{% macro navlink(endpoint, name, active=False) %}
<li {% if endpoint == request.endpoint or active %}class="active"{% endif %}>
    <a href={{ url_for(endpoint) }}>{{ name }}</a>
</li>
{% endmacro %}

{% macro tablink_href(endpoint, name, active=False) %}
<li {% if endpoint == request.endpoint or active %}class="active"{% endif %} >
    <a href={{ endpoint }} role="tab" data-toggle="tab">{{ name }}</a>
</li>
{% endmacro %}

{% macro render_pagination(page_obj, url, ul_class='') %}
<ul class='{%- if ul_class -%}{{ ul_class }}{%- else -%}pagination{%- endif -%}'>
    <li class="disabled"><a href="#"><span class="pages-label">Pages:</span></a></li>
    {%- for page in page_obj.iter_pages() %}
        {% if page %}
            {% if page != page_obj.page %}
                <li><a href="{{ url }}?page={{ page }}">{{ page }}</a></li>
            {% else %}
                <li class="active"><a href="#">{{ page }}</a></li>
            {% endif %}
        {% endif %}
    {%- else -%}
        <li class="active"><a href="#">1</a></li>
    {%- endfor %}
    {% if page_obj.has_next %}
        <li><a href="{{ url }}?page={{ page_obj.next_num }}">&raquo;</a></li>
    {% endif %}
</ul>
{% endmacro %}


{% macro render_topic_pagination(page_obj, url) %}
<ul class="pagination pagelink pull-left">
    <li class="disabled"><a><span class="pages-label">Pages: </span></a></li>
    {%- for page in page_obj.iter_pages() %}
        {% if page %}
            {% if page != page_obj.page %}
                <li><a href="{{ url }}?page={{ page }}">{{ page }}</a></li>
            {% else %}
                <li class="disabled"><a href="#">{{ page }}</a></li>
            {% endif %}
        {% endif %}
    {%- else -%}
        <li class="disabled"><a href="#">1</a></li>
    {%- endfor %}
    {% if page_obj.has_next %}
        <li><a href="{{ url }}?page={{ page_obj.next_num }}">Next</a></li>
    {% endif %}
</ul>
{% endmacro %}


{% macro message_pagination(page_obj, url) %}
<ul class='{%- if ul_class -%}{{ ul_class }}{%- else -%}pagination pagination-sm{%- endif -%}'>
    {%- for page in page_obj.iter_pages() %}
        {% if page %}
            {% if page != page_obj.page %}
                <li><a href="{{ url }}?page={{ page }}">{{ page }}</a></li>
            {% else %}
                <li class="active"><a href="#">{{ page }}</a></li>
            {% endif %}
        {% endif %}
    {%- else -%}
        <li class="active"><a href="#">1</a></li>
    {%- endfor %}
    {% if page_obj.has_next %}
        <li><a href="{{ url }}?page={{ page_obj.next_num }}">&raquo;</a></li>
    {% endif %}
</ul>
{% endmacro %}


{%- macro topic_pages(topic_obj, per_page=10) -%}
{% set topic_pages = (topic_obj.post_count / per_page)|round|int %}
{%- if topic_pages >  1 -%}
<small>[
    {% for page in range(0, topic_pages) %}
            <a href="{{ url_for('forum.view_topic', topic_id=topic_obj.id) }}?page={{ page+1 }}">{{ page+1 }} </a>
    {% endfor %}
]</small>
{%- endif -%}
{%- endmacro -%}

openspending/templates/forum/navigation.html
{%- from "forum/macros.html" import topnav with context -%}
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">FlaskBB</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">



            </ul>

        {% if current_user and current_user.is_authenticated() %}
            <div class="btn-group navbar-btn navbar-right" style="padding-left: 15px; margin-right: -10px">
                <a class="btn btn-primary" href="{{ url_for('account.profile', account_id=current_user.id) }}">
                    <span class="fa fa-user"></span> {{ current_user.username }}
                </a>
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{ url_for('forum.topictracker') }}"><span class="fa fa-book"></span> Topic Tracker</a></li>
                    <li class="divider"></li>

               
                    <li><a href="{{ url_for('account.logout') }}"><span class="fa fa-power-off"></span> Logout</a></li>
                </ul>
            </div>


        {% else %}
            <div class="btn-group navbar-btn navbar-right">
                <a class="btn btn-primary" href="{{ url_for('account.login') }}">
                    <span class="fa fa-user"></span> Login
                </a>
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
            </div>
        {% endif %}
        </div><!-- nav-collapse -->
    </div><!-- container -->
</nav> <!-- navbar navbar-inverse -->