openspending/views/admin.py
import colander
from flask import Blueprint, render_template, request, redirect, Response
from flask.ext.login import current_user
from flask import current_app

from openspending.auth import require, admin_required


from wtforms import Form, TextField, PasswordField, validators

from openspending.model import Dataset
from openspending.admin.helpers import LoadReport



blueprint = Blueprint('findadmin', __name__)



@blueprint.route('/findadmin/dataloader', methods=['GET'])
@admin_required
def dataloader():
    """ Render the login/registration page. """
    return render_template('findadmin/index.html')





@blueprint.route('/findadmin/report')
@admin_required
def report():
    dataset_id = request.args.get("id", None)
    if not dataset_id:
        raise
    dataset = Dataset.by_id(dataset_id)
    if not dataset:
        raise
    lr = LoadReport(dataset)
    return Response(lr.get_output(),
                mimetype='application/zip',
                headers={'Content-Disposition':'attachment;filename=%s.zip'%dataset.name})

openspending/templates/adminsection/qalist.html
{% extends 'admin/master.html' %}
{% import 'admin/lib.html' as lib with context %}
{% import 'admin/static.html' as admin_static with context%}
{% import 'admin/model/layout.html' as model_layout with context %}
{% import 'admin/actions.html' as actionlib with context %}

{% block head %}
    {{ super() }}
    {{ lib.form_css() }}
{% endblock %}


{% macro render_qalist(model, column) %}
    <a target='_blank' href='{{ url_for("dataset.edit_view", id=model.dataset.id) }}'>{{ model.dataset.label }}</a>

{% endmacro %}

{% macro render_report(model, column) %}
    <a target='_blank' href='{{ url_for("findadmin.report", id=model.dataset.id) }}'>QA Report</a>

{% endmacro %}

{% macro num_log_records(model, column) %}
    {% if model.dataset.source.runs.first() %}
        {{ model.dataset.source.runs.first().records.count() }}
    {% else %}
        Error
    {% endif %}

{% endmacro %}


{% macro render_sourceurl(model, column) %}
    {% if model.rawfile %}
        <a target="_blank" href="{{ model.rawfile.get_url() }}">Uploaded File</a>
    {% elif model.url %}
        <a target="_blank" href="{{ model.url }}">External Source</a>
    {% else %}
        <p>No data</p>
    {% endif %}

{% endmacro %}

{% block body %}
    {% block model_menu_bar %}
    <ul class="nav nav-tabs actions-nav">
        <li class="active">
            <a href="javascript:void(0)">{{ _gettext('List') }} ({{ count }})</a>
        </li>
        {% if admin_view.can_create %}
        <li>
            <a href="{{ get_url('.create_view', url=return_url) }}" title="{{ _gettext('Create new record') }}">{{ _gettext('Create') }}</a>
        </li>
        {% endif %}

        {% if filters %}
        <li class="dropdown">
            {{ model_layout.filter_options() }}
        </li>
        {% endif %}

        {% if actions %}
        <li class="dropdown">
            {{ actionlib.dropdown(actions) }}
        </li>
        {% endif %}

        {% if search_supported %}
        <li>
            {{ model_layout.search_form() }}
        </li>
        {% endif %}
    </ul>
    {% endblock %}

    {% if filters %}
        {{ model_layout.filter_form() }}
        <div class="clearfix"></div>
    {% endif %}

    {% block model_list_table %}
    <table class="table table-striped table-bordered table-hover model-list">
        <thead>
            <tr>
                {% block list_header scoped %}
                    {% if actions %}
                    <th class="list-checkbox-column">
                        <input type="checkbox" name="rowtoggle" class="action-rowtoggle" title="{{ _gettext('Select all records') }}" />
                    </th>
                    {% endif %}
                    {% block list_row_actions_header %}
                    <th class="span1">&nbsp;</th>
                    {% endblock %}
                    {% set column = 0 %}
                    {% for c, name in list_columns %}
                    <th class="column-header">
                        {% if admin_view.is_sortable(c) %}
                            {% if sort_column == column %}
                                <a href="{{ sort_url(column, True) }}" title="{{ _gettext('Sort by %(name)s', name=name) }}">
                                    {{ name }}
                                    {% if sort_desc %}
                                        <i class="icon-chevron-up"></i>
                                    {% else %}
                                        <i class="icon-chevron-down"></i>
                                    {% endif %}
                                </a>
                            {% else %}
                                <a href="{{ sort_url(column) }}" title="{{ _gettext('Sort by %(name)s', name=name) }}">{{ name }}</a>
                            {% endif %}
                        {% else %}
                            {{ name }}
                        {% endif %}
                        {% if admin_view.column_descriptions.get(c) %}
                            <a class="icon-question-sign"
                               title="{{ admin_view.column_descriptions[c] }}"
                               href="javascript:void(0)" data-role="tooltip"
                            ></a>
                        {% endif %}
                    </th>
                    {% set column = column + 1 %}
                    {% endfor %}
                {% endblock %}
            </tr>
        </thead>
        {% for row in data %}
        <tr>
            {% block list_row scoped %}
                {% if actions %}
                <td>
                    <input type="checkbox" name="rowid" class="action-checkbox" value="{{ get_pk_value(row) }}" title="{{ _gettext('Select record') }}" />
                </td>
                {% endif %}
                {% block list_row_actions_column scoped %}
                <td>
                    {% block list_row_actions scoped %}
                        {%- if admin_view.can_edit -%}
                        <a class="icon" href="{{ get_url('.edit_view', id=get_pk_value(row), url=return_url) }}" title="{{ _gettext('Edit record') }}">
                            <i class="icon-pencil"></i>
                        </a>
                        {%- endif -%}
                        {%- if admin_view.can_delete -%}
                        <form class="icon" method="POST" action="{{ get_url('.delete_view') }}">
                            {{ delete_form.id(value=get_pk_value(row)) }}
                            {{ delete_form.url(value=return_url) }}
                            {{ delete_form.csrf_token }}
                            <button onclick="return confirm('{{ _gettext('Are you sure you want to delete this record?') }}');" title="{{ _gettext('Delete record') }}">
                                <i class="icon-trash"></i>
                            </button>
                        </form>
                        {%- endif -%}
                    {% endblock %}
                </td>
                {% endblock %}
                
                {% for c, name in list_columns %}
                    {% if admin_view.is_editable(c) %}
                        {% if form.csrf_token %}
                        <td>{{ form[c](pk=get_pk_value(row), value=get_value(row, c), csrf=form.csrf_token._value()) }}</td>
                        {% else %}
                        <td>{{ form[c](pk=get_pk_value(row), value=get_value(row, c)) }}</td>
                        {% endif %}
                    {% else %}
                    <td>{{ get_value(row, c) }}</td>
                    {% endif %}
                {% endfor %}
            {% endblock %}
        </tr>
        {% else %}
        <tr>
            <td colspan="999">
                {% block empty_list_message %}
                <div class="text-center">
                    {{ admin_view.get_empty_list_message() }}
                </div>
                {% endblock %}
            </td>
        </tr>
        {% endfor %}
    </table>
    {{ lib.pager(page, num_pages, pager_url) }}
    {% endblock %}

    {{ actionlib.form(actions, get_url('.action_view')) }}
{% endblock %}

{% block tail %}
    {{ super() }}
    {{ lib.form_js() }}
    <script src="{{ admin_static.url(filename='admin/js/filters-1.0.0.js') }}"></script>

    {{ actionlib.script(_gettext('Please select at least one record.'),
                        actions,
                        actions_confirmation) }}

    <script language="javascript">
        (function($) {
            $('[data-role=tooltip]').tooltip({
                html: true,
                placement: 'bottom'
            });
            {% if filter_groups %}
                var filter = new AdminFilters(
                    '#filter_form', '.field-filters',
                    {{ filter_groups|tojson|safe }},
                    {{ active_filters|tojson|safe }}
                );                
            {% endif %}
        })(jQuery);
    </script>
{% endblock %}